import {
  Sparkles,
  ArrowUpRight,
} from "lucide-react";

function AIRecommendations({
  analysis,
}: {
  analysis: any;
}) {

  return (
    <div className="relative overflow-hidden bg-white/[0.03] border border-white/10 rounded-[32px] p-8 backdrop-blur-2xl">

      <div className="absolute bottom-0 right-0 w-64 h-64 bg-[#FB3640]/10 blur-3xl rounded-full" />

      <div className="relative z-10">

        <div className="flex items-center gap-4">

          <div className="w-14 h-14 rounded-2xl bg-[#FB3640]/15 border border-[#FB3640]/20 flex items-center justify-center">

            <Sparkles
              size={24}
              className="text-[#FB3640]"
            />

          </div>

          <div>

            <h2 className="text-3xl font-bold">
              AI Recommendations
            </h2>

            <p className="text-gray-400 mt-2">
              Strategic improvements generated by AI
            </p>

          </div>

        </div>

        <div className="mt-10 space-y-5">

          {analysis?.improvementSuggestions?.length > 0 ? (

            analysis.improvementSuggestions.map(
              (
                suggestion: string,
                index: number
              ) => (

                <div
                  key={index}
                  className="group bg-black/20 border border-white/10 rounded-3xl p-6 hover:border-[#FB3640]/20 hover:bg-white/[0.03] transition-all duration-300"
                >

                  <div className="flex items-start justify-between gap-5">

                    <div>

                      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#FB3640]/10 border border-[#FB3640]/10 text-xs uppercase tracking-wide text-[#FB3640] mb-4">

                        AI Suggestion

                      </div>

                      <p className="text-gray-200 leading-relaxed text-[15px]">
                        {suggestion}
                      </p>

                    </div>

                    <div className="w-10 h-10 rounded-xl bg-white/[0.03] border border-white/10 flex items-center justify-center group-hover:bg-[#FB3640]/10 group-hover:border-[#FB3640]/20 transition-all duration-300">

                      <ArrowUpRight
                        size={18}
                        className="text-gray-400 group-hover:text-[#FB3640] transition-all duration-300"
                      />

                    </div>

                  </div>

                </div>

              )
            )

          ) : (

            <div className="bg-black/20 border border-white/10 rounded-3xl p-8 text-gray-400 leading-relaxed">

              Upload your resume to receive AI-generated
              recommendations and optimization strategies.

            </div>

          )}

        </div>

      </div>

    </div>
  );
}

export default AIRecommendations;